{
 "title": "Assisted Events Scrape",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Events Scraper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container=\"assisted-events-scrape\"}[$interval]))",
     "legendFormat": "Cpu usage avg"
    },
    {
     "expr": "stddev(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"${namespace}\",container=\"assisted-events-scrape\"}[$interval]))",
     "legendFormat": "Cpu usage stddev"
    },
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"${namespace}\",container=\"assisted-events-scrape\"}[$interval]))",
     "legendFormat": "Throttling"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"${namespace}\",container=\"assisted-events-scrape\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"assisted-installer-${environment}\",container=\"assisted-events-scrape\",resource=\"memory\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"assisted-installer-${environment}\",container=\"assisted-events-scrape\",resource=\"memory\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_restarts_total{namespace=\"${namespace}\",container=\"assisted-events-scrape\"}) by (pod)",
     "legendFormat": "Restarts {{ pod }}"
    },
    {}
   ]
  },
  {
   "title": "RX/TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"${namespace}\",pod=~\"assisted-events-scrape.*\"}[$interval])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"${namespace}\",pod=~\"assisted-events-scrape.*\"}[$interval])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "[PRODUCTION] Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "[PROD] Error log",
     "type": "logs",
     "description": "Errors from stage environment",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expression": "fields message\n| filter message like '\"levelname\": \"ERROR\"'\n| filter kubernetes.container_name = \"assisted-events-scrape\" and kubernetes.namespace_name = \"assisted-installer-production\"\n| sort @timestamp desc\n| limit 100",
       "logGroupNames": [
        "app-sre-prod-04-5ts49.application"
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    },
    {
     "title": "[PROD] Log tail",
     "type": "logs",
     "description": "Errors from stage environment",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expression": "fields message\n| filter kubernetes.container_name = \"assisted-events-scrape\" and kubernetes.namespace_name = \"assisted-installer-production\"\n| sort @timestamp desc\n| limit 100",
       "logGroupNames": [
        "app-sre-prod-04-5ts49.application"
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "[STAGE] Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "[STAGE] Error log",
     "type": "logs",
     "description": "Errors from stage environment",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expression": "fields message\n| filter kubernetes.container_name = \"assisted-events-scrape\" and kubernetes.namespace_name = \"assisted-installer-stage\"\n| filter message like '\"levelname\": \"ERROR\"'\n| sort @timestamp desc\n| limit 100",
       "logGroupNames": [
        "app-sre-stage-0-ctbn8.application"
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    },
    {
     "title": "[STAGE] Error log",
     "type": "logs",
     "description": "Errors from stage environment",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expression": "fields message\n| filter kubernetes.container_name = \"assisted-events-scrape\" and kubernetes.namespace_name = \"assisted-installer-stage\"\n| sort @timestamp desc\n| limit 100",
       "logGroupNames": [
        "app-sre-stage-0-ctbn8.application"
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    }
   ]
  }
 ]
}